apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Release.Name }}-{{ .Chart.Name }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: App__SelfUrl
          value: "{{ .Values.config.selfUrl }}"
        - name: App__AngularUrl
          value: "{{ .Values.config.angularUrl }}"        
        - name: App__CorsOrigins
          value: "{{ .Values.config.corsOrigins }}"
        - name: App__DisablePII
          value: "{{ .Values.config.disablePII }}"
        - name: App__HealthCheckUrl
          value: "{{ .Values.config.healthCheckUrl }}"
        - name: "ConnectionStrings__Default"
          value: "{{ .Values.config.connectionStrings.default }}"
        - name: "AuthServer__RequireHttpsMetadata"
          value: "{{ .Values.config.authServer.requireHttpsMetadata }}"
        - name: "AuthServer__Authority"
          value: "{{ .Values.config.authServer.authority }}"
        - name: "App__RedirectAllowedUrls"
          value: "{{ .Values.config.redirectAllowedUrls }}"
        - name: "DOTNET_ENVIRONMENT"
          value: "{{ .Values.config.dotnetEnv }}"
        - name: "Redis__Configuration"
          value: "{{ .Values.config.redisHost }}"
        - name: "ASPNETCORE_URLS"
          value: "{{ .Values.config.aspnetCoreUrls }}"
          {{- if .Values.env }}
{{ toYaml .Values.env | indent 8 }}
          {{- end }}
        