apiVersion: v1
kind: Pod
metadata: 
  name: firstpod
  labels:
    app: front-end
    team: developer
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
