apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  # serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssql
      securityContext:
        fsGroup: 10001
      containers:
        - image: mcr.microsoft.com/mssql/server:2019-latest
          name: {{ .Release.Name }}-{{ .Chart.Name }}
          volumeMounts:
          - mountPath: /var/opt/mssql
            name: mssqldb
          ports:
          - name: mssql
            containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Developer"
          - name: SA_PASSWORD
            value: "myPassw@rd"
          - name: ACCEPT_EULA
            value: "Y"
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
