apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  activeDeadlineSeconds: 180
  template:
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Release.Name }}-{{ .Chart.Name }}
        env:
        - name: "ConnectionStrings__Default"
          value: {{ .Values.config.connectionStrings.default }}
        - name: "OpenIddict__Applications__AzureAppsAngular_App__RootUrl"
          value: {{ .Values.config.openIddictApplications.azureAppsAngularAppRootUrl }}
        - name: "OpenIddict__Applications__AzureAppsAngular_Swagger__RootUrl"
          value: {{ .Values.config.openIddictApplications.azureAppsAngularSwaggerRootUrl }}
        - name: "Redis__Configuration"
          value: {{ .Values.config.redisConfiguration }}
          {{- if .Values.env }}
{{ toYaml .Values.env | indent 8 }}
          {{- end }}

      restartPolicy: Never
  backoffLimit: 10

  